name: run
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: 1 17 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 50
        # 关键设置：强制时区为北京时间
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run install
      - run: npm run main
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USERID: ${{ secrets.USERID }}
